//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeGo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeoffRequest
    {
        public int TimeoffId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Reason { get; set; }
        public int ApprovalStatusId { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public System.DateTime ReturningToWork { get; set; }
    
        public virtual ApprovalStatus ApprovalStatu { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
