//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeGo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeGoEntities : DbContext
    {
        public TimeGoEntities()
            : base("name=TimeGoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApprovalStatus> ApprovalStatus { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyApproved> CompanyApproveds { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<LockStatus> LockStatus { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<SubscriptionPlan> SubscriptionPlans { get; set; }
        public virtual DbSet<Timesheet> Timesheets { get; set; }
        public virtual DbSet<TimesheetLine> TimesheetLines { get; set; }
        public virtual DbSet<VersionInfo> VersionInfoes { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskAllowed> TaskAlloweds { get; set; }
        public virtual DbSet<EmployeeRate> EmployeeRates { get; set; }
        public virtual DbSet<TimeoffRequest> TimeoffRequests { get; set; }
    }
}
