//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeGo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Timesheet()
        {
            this.TimesheetLines = new HashSet<TimesheetLine>();
        }
    
        public int TimesheetId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> PeriodId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeNotes { get; set; }
        public string ApproverNotes { get; set; }
        public int ApprovalStatusId { get; set; }
        public int LockStatusId { get; set; }
        public Nullable<int> RevisedById { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTime> SavedOn { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
        public Nullable<System.DateTime> RevisedOn { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    
        public virtual ApprovalStatus ApprovalStatu { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual LockStatus LockStatu { get; set; }
        public virtual Period Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimesheetLine> TimesheetLines { get; set; }
    }
}
